[view_parameters]
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
FPS = 60
PEG_RADIUS = 8

[colormaps]
WHITE = [255, 255, 255]
BLACK = [0, 0, 0]
RED = [255, 100, 100]
BLUE = [100, 150, 255]
GREEN = [100, 255, 100]
YELLOW = [255, 255, 100]
ORANGE = [255, 165, 0]
PURPLE = [128, 0, 128]
PINK = [255, 192, 203]
CYAN = [0, 255, 255]
GOLD = [255, 215, 0]
SILVER = [192, 192, 192]
GRAY = [128, 128, 128]

[ball_physics]
gravity = 0.15
bounce = 0.9
friction = 0.98

[peg_distances]
h_spacing = 35
v_spacing = 35